Removed org.hibernate.javax.persistence dependency for fix exception "Caused by: java.lang.NoSuchMethodError: javax.persistence.Table.indexes()[Ljavax/persistence/Index;".